# Generated by Django 4.2.6 on 2023-11-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_proccessinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proccessinfo',
            name='run',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
