# Generated by Django 4.2.6 on 2023-11-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_alter_proccessinfo_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proccessinfo',
            name='stop_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
